name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Test
        run: dotnet test --logger "trx" /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../CoverageResults/lcov.info
      - name: Upload Test Report
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: test-results
          path: test/*.Tests/TestResults/*.trx
          reporter: dotnet-trx
      - name: Write Coverage Report
        if: success() || failure()
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./test/CoverageResults/lcov.info
