name: publish

on:
  push:
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Install versionize
        run: dotnet tool install --global versionize

      - name: Run versionize
        continue-on-error: true
        id: versionize
        run: versionize --changelog-all --exit-insignificant-commits

      - name: No release required
        if: steps.versionize.outcome != 'success'
        run: echo "Skipping publishing. No release required."

      - name: Build package
        if: steps.versionize.outcome == 'success'
        run: dotnet pack --output nupkgs --include-source --configuration Release --include-symbols
      - name: Push changes to GitHub
        if: steps.versionize.outcome == 'success'
        run: git push --follow-tags
